<Project>
  <PropertyGroup>
    <CloudBayVersionFile>$(MSBuildThisFileDirectory)version.json</CloudBayVersionFile>
    <_CloudBayVersionDocument Condition="Exists('$(CloudBayVersionFile)')">$([System.IO.File]::ReadAllText('$(CloudBayVersionFile)'))</_CloudBayVersionDocument>
    <_CloudBayVersionPattern>\A\s*\{\s*&quot;version&quot;\s*:\s*&quot;((?:0|[1-9][0-9]{0,4})\.(?:0|[1-9][0-9]{0,4})\.(?:0|[1-9][0-9]{0,4}))&quot;\s*\}\s*\z</_CloudBayVersionPattern>
    <_CloudBayVersionDocumentValid>$([System.Text.RegularExpressions.Regex]::IsMatch('$(_CloudBayVersionDocument)', '$(_CloudBayVersionPattern)'))</_CloudBayVersionDocumentValid>
    <CloudBayBaseVersion Condition="'$(_CloudBayVersionDocumentValid)' == 'True'">$([System.Text.RegularExpressions.Regex]::Match('$(_CloudBayVersionDocument)', '$(_CloudBayVersionPattern)').Groups[1].Value)</CloudBayBaseVersion>
    <Version Condition="'$(Version)' == ''">$(CloudBayBaseVersion)</Version>
    <CloudBayBuildFlavor Condition="'$(CloudBayBuildFlavor)' == ''">$(Configuration)</CloudBayBuildFlavor>
    <DefineConstants Condition="'$(CloudBayBuildFlavor)' == 'Debug'">$(DefineConstants);CLOUDBAY_DEBUG</DefineConstants>
    <Company>CloudBay</Company>
    <Product>CloudBay</Product>
  </PropertyGroup>
</Project>
