using System.Security.Cryptography;
using System.Text;

namespace CloudBay.Core.Transfers;

internal static class TransferConflictNames
{
    public static bool IsAllowedTarget(TransferUploadRequest request, string target, string provider)
    {
        var original = request.RelativePath.Replace('\\', '/');
        if (target == original) return true;
        if (request.ConflictPolicy != TransferConflictPolicy.Rename) return false;
        if (target == RenamePath(original, request.OperationId)) return true;
        var slash = original.LastIndexOf('/');
        var folder = slash < 0 ? "" : original[..(slash + 1)];
        var name = original[(slash + 1)..];
        // Receipts generated by earlier adapters retain their exact alternate
        // names on recovery; no arbitrary provider-selected path is accepted.
        if (provider == "b2" && request.OperationId.Length == 64 && request.OperationId.All(Uri.IsHexDigit))
            return target == folder + Sync.PathRules.ConflictFileName(name, " (" + request.OperationId[..12] + ")");
        if (provider == "onedrive")
        {
            var suffix = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(request.OperationId)))[..10].ToLowerInvariant();
            var extension = Path.GetExtension(name);
            return target == folder + Path.GetFileNameWithoutExtension(name) + " (CloudBay " + suffix + ")" + extension;
        }
        return false;
    }

    public static string RenamePath(string path, string operationId)
    {
        path = path.Replace('\\', '/');
        var slash = path.LastIndexOf('/');
        var name = path[(slash + 1)..];
        var suffix = operationId.Length == 64 && operationId.All(Uri.IsHexDigit)
            ? operationId[..12].ToLowerInvariant()
            : Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(operationId)))[..12].ToLowerInvariant();
        return (slash < 0 ? "" : path[..(slash + 1)]) + Sync.PathRules.ConflictFileName(name, " (CloudBay " + suffix + ")");
    }
}
